app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[Required()])
    room = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

class LogoutForm(Form):
    submit = SubmitField('Exit Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from flask_bootstrap import Bootstrap

socketio = SocketIO()
bootstrap = Bootstrap()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    bootstrap.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm
from .forms import LogoutForm


@main.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('main.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form)


@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    form = LogoutForm()
    if name == '' or room == '':
        return redirect(url_for('main.chat'))
    return render_template('chat.html', name=name, room=room, form=form)

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% block title %}
    <title>Hello, world!</title>
    {% endblock %}
    {% block head_scripts %}
    {% endblock %}
  </head>
  <body>
{% include 'sub_templates/navbar.html' %}
    {% block content %}
        <h1>Hello, world!</h1>
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block foot_scripts %}
    {% endblock %}
  </body>
</html>

app/templates/chat.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <h1>Flask-SocketIO-Chat: {{ room }}</h1>
    <textarea id="chat" cols="80" rows="20"></textarea><br><br>
    <input id="text" size="80" placeholder="Enter your message here"><br><br>
    <form action="/" class='form' method="GET">
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.submit, class="btn btn-success") }}
    </form>
</div>
{% endblock %}


{% block foot_scripts %}
    {{ super() }}
    {% include 'sub_templates/chat_scripts.html' %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

    <h1>Flask-SocketIO-Chat</h1>
    <form class='form' method="POST">
        {{ form.hidden_tag() }}
        {{ form.name.label }}: {{ form.name() }}
        {% for error in form.name.errors %}{{ error }}{% endfor %}
        <br>
        {{ form.room.label }}: {{ form.room() }}
        {% for error in form.room.errors %}{{ error }}{% endfor %}
        <br>
        {{ wtf.form_field(form.submit, class="btn btn-success") }}
    </form>
</div>
{% endblock %}
{{ wtf.quick_form(form) }}

app/templates/sub_templates/chat_scripts.html
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
    <script type="text/javascript" charset="utf-8">
        var socket;
        $(document).ready(function(){
            socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
            socket.on('connect', function() {
                socket.emit('joined', {});
            });
            socket.on('status', function(data) {
                $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            socket.on('message', function(data) {
                $('#chat').val($('#chat').val() + data.msg + '\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            $('#text').keypress(function(e) {
                var code = e.keyCode || e.which;
                if (code == 13) {
                    text = $('#text').val();
                    $('#text').val('');
                    socket.emit('text', {msg: text});
                }
            });
        });
        function leave_room() {
            socket.emit('left', {}, function() {
                socket.disconnect();

                // go back to the login page
                window.location.href = "{{ url_for('main.index') }}";
            });
        }
    </script>

app/templates/sub_templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">SocketChat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/chat">Chat</a>
      </li>
    </ul>
  </div>
</nav>